// Package websearch provides the universal proxy-managed web search feature.
// It intercepts web_search tool calls across all models and executes them
// via SearXNG with optional Perplexity Sonar Pro summary enrichment.
package websearch

// SearchQuery represents a universal web search request.
// It matches the Claude CLI WebSearch input contract.
type SearchQuery struct {
	// Query is the search query string.
	Query string `json:"query"`

	// AllowedDomains restricts results to these domains only.
	AllowedDomains []string `json:"allowed_domains,omitempty"`

	// BlockedDomains excludes results from these domains.
	BlockedDomains []string `json:"blocked_domains,omitempty"`
}

// SearchResult represents a single search result from any backend.
type SearchResult struct {
	// Title of the search result.
	Title string `json:"title"`

	// URL of the search result.
	URL string `json:"url"`

	// Snippet is a short text excerpt from the result page.
	Snippet string `json:"snippet,omitempty"`

	// PublishedDate is the Unix timestamp of publication if available.
	PublishedDate *int64 `json:"published_date,omitempty"`

	// Domain is the hostname extracted from URL.
	Domain string `json:"domain,omitempty"`

	// Source identifies which backend produced this result ("searxng" or "perplexity").
	Source string `json:"source"`
}

// SearchResponse is the universal response from the search orchestrator.
// It combines raw SearXNG results with an optional Perplexity summary.
type SearchResponse struct {
	// Results contains the normalized search results.
	Results []SearchResult `json:"results"`

	// TotalResults is the total number of results available (may exceed len(Results)).
	TotalResults int `json:"total_results"`

	// Query echoes the original search query.
	Query string `json:"query"`

	// SummaryHeader is an optional concise summary generated by Perplexity.
	// Empty when Perplexity is not configured or fails.
	SummaryHeader string `json:"summary_header,omitempty"`

	// Error contains an error message if the search partially or fully failed.
	Error *string `json:"error,omitempty"`
}
